### ISSUE TITLE
Move to API Gateway 

### ISSUE THREAD

**Issue by bryan-harter** [IMAP-Science-Operations-Center/sds-data-manager#43]
Spin up API Gateway architecture in the CDK rather than Lambda URLs

**Comment by laspsandoval** [comment]
An API Gateway is beneficial because spinning up an API Gateway architecture in the CDK rather than using Lambda URLs directly gives you better control over your API's routing, security, and other features:

1. Efficient routing and versioning: With API Gateway, you can route different URL paths or request types to different Lambda functions. You can also manage different versions of your API more effectively.
2. Throttling and scaling: API Gateway provides built-in throttling to protect your back-end services. It also helps manage the scaling of your services.
3. Security: API Gateway provides several features that allow you to create more secure APIs, such as AWS IAM roles and policies, Amazon Cognito user pools, AWS WAF (a web application firewall), and resource policies.
4. Monitoring and troubleshooting: API Gateway integrates with Amazon CloudWatch and AWS X-Ray allowing you to monitor API usage and troubleshoot potential issues.

**Comment by laspsandoval** [comment]
To transfer the domain:
https://repost.aws/knowledge-center/account-transfer-route-53#:~:text=You%20can%20transfer%20a%20domain,domain%20by%20contacting%20AWS%20Support.&text=Create%20a%20new%20hosted%20zone%20in%20an%20AWS%20account%20that%20you%20own.

**Comment by laspsandoval** [comment]
Here are the steps to request a new SSL certificate in your new account:

Navigate to AWS Certificate Manager in your AWS Console.
Click on "Request a certificate".
Select "Request a public certificate" and click "Request a certificate".
On the next screen, in the "Add domain names" section, add your domain name. If you plan to have subdomains and you want the certificate to cover them, you can use a wildcard by entering "*.imap-mission.com". If you don't plan to have subdomains, just enter "imap-mission.com".
Click "Next".
On the next page, select "DNS validation".
Click "Review", review your settings, and then click "Confirm and request".
On the validation page, you'll see a CNAME record that you need to add to your Route 53 DNS records for imap-mission.com. This proves to ACM that you have control over the domain.
After you add the CNAME record to Route 53, the Certificate Manager will automatically validate it and issue the SSL certificate, which you can use in your API Gateway setup.

Once the certificate is issued, you'll be able to select it in API Gateway custom domain setup in the same account.

Remember, SSL certificates are region-specific, so make sure to request the certificate in the same region where you're setting up your API Gateway.

Finally, it's worth noting that you cannot transfer SSL certificates between AWS accounts; they're tied to the account where they were issued.

**Comment by laspsandoval** [comment]
Note: I will make updates according to the results of ruff and black next week. Happy 4th!

**Comment by bryan-harter** [comment]
This one is definitely done!
