### ISSUE TITLE
SPIKE - Processing infrastucture and priorities

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/sds-data-manager#74]
## Description

This spike should explore a few different options for the infrastructure for running the data processing. This spike will have to be a little less specific than the other infra spikes, because we don't fully know what the processing requirements will be. So, this spike can overall keep things general, and explore the pros and cons of event vs batch processing in general rather than come up with specific designs for what the exact pieces of the processing pipeline will need to be. It might be best to complete this spike ahead of the others, as in particular #71 might change based on the outcome of this ticket. 

## Requirements
- Examine some designs for the processing code, to allow for comparing and contrasting later
- The processing code should include designs for event driven as well as batch processing, and explore different timing requirements
- The system will need to reprocess data if processing fails or if the Spice kernels are updated
- There should be some discussion about monitoring the system

### Nice to have or Goal Requirements
- Determine if the processing pipelines will attempt to always succeed, or if they might have a system for failing quickly if they don't have the correct data
- Explore AWS Batch vs AWS Step functions
- Describe what scaling would look like in each system
- Describe what code could be shared between instruments, if any

## Additional notes
- We expect the system to receive batches of L0 files 2-3 times a week
- Keep in mind that the system may need to wait for multiple sources of data, which may not be available at the same time

## Related tickets
- #68 
- #71
- #72

## Follow up tickets
This spike is not considered complete until at least one follow up issue is created. 
- SPIKE - Processing infrastucture and priorities part #153 

**Below is the template for the response to this ticket. Add as many solutions as needed, but preferably include 2-5 for discussion. The response should be posted as a comment on this issue, or linked in a comment. **

# Solution 1
https://lasp.colorado.edu/galaxy/display/IMAP/SDC+Processing+Architecture+Overview

## Pros:
- Modularized by constructs

## Cons:
- Each construct will require inherent logic

## Additional notes:
- note

# Solution 2
We could make a lot of Stacks.

## Pros:
- Simple stacks

## Cons:
- Lots of duplication

## Additional notes:
- Here is a start on how processing will be triggered and database tables:
https://lasp.colorado.edu/galaxy/pages/viewpage.action?pageId=173708100
https://lasp.colorado.edu/galaxy/display/IMAP/SDC+Database+Tables

# Summary
Write up a summary of your findings, including your preferred solution.

**Comment by GFMoraga** [comment]
**AWS Batch:**

Pros:
- Scalable Batch Processing: AWS Batch simplifies the execution of large-scale batch processing workloads by automatically provisioning and managing compute resources based on job requirements.
- Resource Optimization: It optimizes resource utilization by dynamically scaling resources up or down based on the workload, allowing you to **maximize cost-efficiency**.
- Job Queue Management: AWS Batch provides built-in job queue management, enabling you to **prioritize and control** the execution order of your batch jobs.
- Integration with AWS Services: It **integrates well** with other AWS services, such as Amazon S3, Amazon DynamoDB, and AWS CloudFormation, allowing you to leverage their capabilities in your batch processing workflows.

Cons:
- Limited Workflow Capabilities: AWS Batch primarily focuses on batch processing and **lacks advanced workflow** management features, such as state management, retries, and error handling.
- Configuration Complexity: Setting up and configuring **AWS Batch can be complex**, especially when defining compute environments, job queues, and job definitions.
- Lack of Visualization: AWS Batch **doesn't provide a graphical interface** to visually design and monitor workflows. It relies more on the command-line interface (CLI) and API-based interaction.

**AWS Step Functions:**

Pros:
- Workflow Orchestration: AWS Step Functions offers powerful workflow orchestration capabilities, allowing you to coordinate and manage complex **workflows across multiple services** and components.
- Visual Workflow Design: It provides a **visual interface for designing workflows** using a state machine model, making it easier to define and understand the flow of tasks and actions.
- Error Handling and Retry Logic: Step Functions include **built-in error handling and retry mechanisms**, enabling you to handle failures and recover from errors automatically.
- Integration with AWS Services: Step Functions **seamlessly integrates** with various AWS services, enabling you to easily incorporate Lambda functions, ECS tasks, SNS notifications, and more into your workflows.

Cons:
- Stateless: Step Functions are **stateless by design**, which means you need to manage and persist any required state externally, such as in a database or using AWS services like DynamoDB or Step Functions service integration patterns.
- Additional Complexity for Simple Workflows: If you have simple, linear workflows without the need for advanced orchestration features, using Step Functions might introduce **unnecessary complexity**.
- Cost Considerations: AWS Step Functions **pricing is based on the number of state transitions**, so if you have highly complex and long-running workflows with frequent state transitions, the costs may increase.

**Comment by laspsandoval** [comment]
Created draft architecture (shown in link above). Next step is to write CDK code to create the architecture and see how it works with different scenarios.
